# Change these first
owner: roink # Your GitHub organization or username, where this repository lives
repo: zootracker-upptime # The name of this repository

sites:
  - name: ZooTracker
    url: https://zootracker.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /zootracker-upptime
  name: ZooTracker Status
  introTitle: "Stay informed about the health of ZooTracker services."
  introMessage: We publish real-time uptime information about our applications and infrastructure so you always know how ZooTracker is performing.
  footer: Maintained by the ZooTracker team.
  navbar:
    - title: Status
      href: /zootracker-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: ZooTracker
      href: https://zootracker.app 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
